
name: Terraform State Backup

on:
  schedule:
    - cron: "0 1 * * *"   # Daily at 1 AM
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Download Terraform state
      run: |
        aws s3 cp s3://my-tf-bucket/prod/terraform.tfstate ./terraform.tfstate

    - name: Copy to backup location
      run: |
        DATE=$(date +'%Y-%m-%d-%H-%M')
        aws s3 cp ./terraform.tfstate s3://my-tf-backups/prod/terraform-$DATE.tfstate

